---
# tasks file for nginx

- name: install nginx
  yum: 
    name: nginx
    state: latest

- name: configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: start nginx
  service:
    name: nginx
    state: restarted
    enabled: true
    
