---

- hosts: localhost
  roles:
    - bastion
  tags: bastion

- hosts: loadbalancer
  roles:
    - nginx
  tags: nginx
- hosts: loadbalancer
  roles:
    - haproxy
  tags: haproxy

- hosts: localhost
  roles:
    - ocp
  tags: ocp

- hosts: localhost
  roles:
    - terraform
  tags: terraform
