---
# tasks file for terraform

- name: install yum-utils
  yum:
    name: yum-utils
    state: latest

- name: yum clean all
  command: yum clean all
  changed_when: false

- name: add hashicorp repo
  command: yum-config-manager --add https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
  changed_when: false

- name: install terraform
  yum:
    name: terraform
    state: latest

- name: install terraform  auto completion
  command: terraform -install-autocomplete
  register: result
  failed_when: false
  changed_when: ('"already installed" not in result.stderr') or (result.rc == 0)

